---
services:
  nautobot:
    image: "${NAUTOBOT_IMAGE_NAME}"
    build:
      context: "../"
      dockerfile: "docker/nautobot.dockerfile"
      args:
        NAUTOBOT_REGISTRY_URL: "${NAUTOBOT_REGISTRY_URL}"
        NAUTOBOT_VERSION: "${NAUTOBOT_VERSION}"
        PYTHON_VERSION: "${PYTHON_VERSION}"
        PYTHON_SUPPORTED_RANGE: "${PYTHON_SUPPORTED_RANGE}"
      target: "nautobot"
